const skills = [
    {id: 1, title: 'HTML'},
    {id: 2, title: 'CSS'},
    {id: 3, title: 'JavaScript'},
    {id: 4, title: 'ReactJs'},
    {id: 5, title: 'TailwindCSS'},
    {id: 6, title: 'GIT'},
    {id: 7, title: 'Github'},
    {id: 8, title: 'TypeScript'},
    {id: 9, title: 'Next.js'},  
    {id: 10, title: 'ExpressJs'},
    {id: 11, title: 'MongoDB'},
    {id: 12, title: 'Redux'},
    {id: 13, title: 'MySQL'},
    {id: 14, title: 'Python'},
    {id: 15, title: 'Flask'},
    {id: 16, title: 'React Native'},
    {id: 17, title: 'Mongoose'},
    {id: 18, title: 'AWS Technologies'},
    {id: 19, title: 'Problem Solving'},
    {id: 20, title: 'Code Debugging'},
    {id: 21, title: 'UI Improvement'},
]

export default skills;